$env:ANTHROPIC_BEDROCK_BASE_URL = "https://apis.huit.harvard.edu/ais-bedrock-llm/v2"
$env:ANTHROPIC_API_KEY = "YourKeyHere"
$env:ANTHROPIC_MODEL = "us.anthropic.claude-opus-4-5-20251101-v1:0"
$env:ANTHROPIC_SMALL_FAST_MODEL = "us.anthropic.claude-opus-4-5-20251101-v1:0"
$env:CLAUDE_CODE_SKIP_BEDROCK_AUTH = "1"
$env:CLAUDE_CODE_USE_BEDROCK = "1"
